### ISSUE TITLE
すたンプを文字で検索できるようにするアイディア

### ISSUE THREAD

**Issue by progre** [rgx6/mouneyou#3]
例えば普段は見えない透明の隠し文字を仕込んどくことで実現できそうです。

![image](https://user-images.githubusercontent.com/1272114/87228132-1886dd80-c3da-11ea-854e-cc7f281b3cb7.png)

![image](https://user-images.githubusercontent.com/1272114/87228157-35bbac00-c3da-11ea-842f-7c3bc1ba66d5.png)

![image](https://user-images.githubusercontent.com/1272114/87228158-381e0600-c3da-11ea-95d3-57d4d89b64e1.png)

これは普段は見えず、 `Ctrl+F` で検索掛けたり `Ctrl+A` などで選択すると見えます。

**Comment by rgx6** [comment]
だいぶ遅くなりましたが、提案頂いた方法と、画面一番下の「すたンプ検索」ボタンからの検索と、2種類作ってみました。

**Comment by progre** [comment]
よさそう。

ブラウザ検索でもヒットしたら赤枠強調できないかなと軽く調べてみましたが、見つけられず。ブラウザ検索のヒットでは :hover とか :active はつかない模様（macOS Firefox）

**Comment by rgx6** [comment]
僕も調べてみましたが見つかりませんでした……
とりあえずこれでクローズしますね。
ありがとうございました。
